name: Deploy Resume to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch if needed
    paths:
      - "resume.html"  # Triggers only when resume.html is updated
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Deploys all files, including resume.html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
