name: Deploy Resume to GitHub Pages

on:
  push:
    branches:
      - main  # Change if using a different branch
    paths:
      - "resume.html"  # Trigger only when resume.html changes
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3  # ✅ Latest version is v3

      - name: Upload Resume HTML
        uses: actions/upload-pages-artifact@v2  # ✅ Latest version is v2
        with:
          path: .  # Deploys all files in the repo

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2  # ✅ Latest version is v2
