# Simple workflow for deploying resume.html to GitHub Pages
name: Deploy Resume to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - "resume.html"  # Trigger only when resume.html changes
  # Allows manual trigger from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping queued runs between in-progress and latest
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload resume.html
        uses: actions/upload-pages-artifact@v3
        with:
          path: "resume.html"  # ✅ Upload only resume.html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
